### ISSUE TITLE
Not grabbing Post(s) links 

### ISSUE THREAD

**Issue by Tanuj69** [Tanuj69/instagram-api#2]
Not sure if it is a puppeteer's issue really or what. The query works perfectly fine on devtools @ instagram.com though

**Comment by rcsm** [comment]
Hey @Tanuj69! I'd like to claim this issue.

**Comment by Tanuj69** [comment]
Sure @rcsm go ahead!

**Comment by Tanuj69** [comment]
Sure @rcsm go ahead! ignore the poor code I was a beginner to promises/async-await at that time.

**Comment by rcsm** [comment]
Great! Relax @Tanuj69 , I'm not a senior either haha.

**Comment by Tanuj69** [comment]
I'll start refactoring as some people are using it now as I see on the npm page

**Comment by rcsm** [comment]
That's cool :100:
