### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Nishkalkashyap** [Tanuj69/instagram-api#7]
Are you willing to convert this project into a typescript project? If so, I can convert and submit a pull request. Let me know if you're interested.

**Comment by Tanuj69** [comment]
Let's make a separate branch for ts translated code. I'm not familiar with ts currently. I can look up your code and see what's what then we can merge

**Comment by Nishkalkashyap** [comment]
Have submitted a pull request. See #8

**Comment by Tanuj69** [comment]
created new branch tsc-src and merged
